### PR TITLE
Added option to hide the progressbar

### PR DESCRIPTION
**Pull request by PeterMosmans**
--hide-progressbar: default False

### CODE REVIEW

**Comment by droope** [comment]
Hi there,

I am OK with this change. If you can add a test for it I am happy to merge it. The test is likely to be similar to https://github.com/droope/droopescan/blob/master/dscan/tests/base_http_tests.py#L198 , except that it will verify that hide_progressbar was passed to the ennumerate( method.

Thanks!
Pedro

**Comment by droope** [comment]
Hi,

I've added an option for hiding the progressbar (--hide-progressbar)

The code changes will be present on droopescan's next release.

**Comment by PeterMosmans** [comment]
Thanks @droope - much, much appreciated :thumbsup:

**Comment by droope** [comment]
No worries, I've released 1.37.1 that adds the --hide-progressbar option.

**Pull request closed without merging**
