### PR TITLE
Added exception handler for read timeouts

### PR DESCRIPTION
**Pull request by PeterMosmans**
Added a basic exception handler for timeouts from the requests module.

### CODE REVIEW

**Comment by droope** [comment]
Hi @PeterMosmans 

thanks for your contribution, I will look into it before droopescan's next release. Any ideas on why tests are failing for this branch? 

If you could add tests for the new functionality that'd be awesome too

**Comment by PeterMosmans** [comment]
Hi @droope , thanks. I haven't looked at tests (yet), and I'm unsure as to why the tests are failing. Does your code expects a different error (assertion) when no connection can be made ?

**Comment by droope** [comment]
Hi

I think the tests are failing because functionality is failing. If I scan an example site with your branch of the plugin:

<pre>
[root@debian-dev droopescanpeter (timeouthandler)]# ./droopescan scan -u www.example.org -n 100 -e p
[+] Accepted redirect to https://www.example.org/
[+] Site identified as drupal.
[+] No plugins found.
</pre>

With the master branch:

<pre>
[root@debian-dev droopescan (master)]# ./droopescan scan -u www.example.org -n 100 -e p
[+] Accepted redirect to https://www.example.org/
[+] Site identified as drupal.
[+] Plugins found:
    views https://www.example.org/sites/all/modules/views/
        https://www.example.org/sites/all/modules/views/README.txt
        https://www.example.org/sites/all/modules/views/LICENSE.txt
    ctools https://www.example.org/sites/all/modules/ctools/
        https://www.example.org/sites/all/modules/ctools/CHANGELOG.txt
        https://www.example.org/sites/all/modules/ctools/API.txt
	[SNIP..]
</pre>

I think giving a warning instead of throwing an exception would be in line with how droopescan operates (e.g. with 500 errors), so if you add a test and fix the error I'm happy to merge it. The test is likely to be similar to this one: https://github.com/droope/droopescan/blob/master/dscan/tests/base_http_tests.py#L440

**Comment by droope** [comment]
Hi

I've implemented the change you requested (a warning instead of a immediate failure on read timeouts.)

The code changes will be present on droopescan's next release.

**Pull request closed without merging**
